version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app-php8.dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
  docker-dns:
    image: hickskp/docker-dns
    restart: always
    volumes:
      - ./dns:/etc/docker-dns/
    ports:
      - 53:53/udp
  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
    user: "1000:1000"
    working_dir: /var/www/html
  artisan:
    build:
      context: .
      dockerfile: app-php8.dockerfile
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    user: "1000:1000"
    depends_on:
      - mysql
    entrypoint: ['php', '/var/www/html/artisan']